### ISSUE TITLE
Getting this error in lambda function can you please help 

### ISSUE THREAD

**Issue by dhanushshetty009** [DiegoZoracKy/s3-csv-to-json#1]
{
  "errorMessage": "Cannot find module '/var/task/src/aws-lambda'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:474:25)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)"
  ]
}

**Comment by DiegoZoracKy** [comment]
Hi, I'm sorry for the late reply. Did you manage to solve your problem?
